name: Ping URL
description: "Ping URL until maximum trials have exceeded. If result is not 200 until then, fails the action."
inputs:
  url:
    type: string
    required: true
    description: URL to ping
  max_trials:
    type: string
    required: false
    description: Maximum number of trials until action fails
    default: '10'
  delay:
    type: string
    required: false
    description: Delay in seconds between trials
    default: '5'
runs:
  using: docker
  image: Dockerfile
