name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20s

      - name: Failing step
        run: |
          exit 1

      - name: I will be skipped
        if: ${{ success() }}
        run: |
          echo "I will print if any previous step succeed."

      - name: I will execute
        if: ${{ failure() }}
        run: |
          echo "I will print if any previous step fails."

      - name: I will execute always unless cancelled
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print, except when the workflow is cancelled."

      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: |
          echo "I will print only when the workflow is cancelled."