name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
          dry-run:
            type: boolean
            default: false
            description: "Skip deployment and only print build output"
          target:
            type: environment
            required: true
            description: "Skip deployment and only print build output"
          tags:
            type: choice
            options: [v1, v2,v3]
            default: 'v1'
            description: "Release from which to build and deploy"

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tags }} "

    deploy:
        runs-on: ubuntu-latest
        if: ${{ success() && contains(inputs.dry-run, 'false') }}
        environment: target
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }} "
