name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
          use-cache:
            type: boolean
            default: true
            description: "Whether to execute cache step"
          node-version:
             type: choice
             options:
              - 18.x
              - 20.x
              - 21.x
             default: 20.x
             description: "Node version"

# Necessary workflows:
# 1. checkout the code
# 2. install dependencies
# 3. unit testing, and building
# 4. deploy to nonprod environment to check whether everything works correctly

jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: 13-caching/react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run:  npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"

  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.output1 }}
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
         node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: |
         echo "$CACHE_KEY"
         echo  "deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> $CACHE_KEY
         echo "output1=value1" >> $"CACHE_KEY"
         cat  "$CACHE_KEY"
      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-key.outputs.cache-hit != 'true' 
        run: npm ci
    
  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3 
        with:
            path: 13-caching/react-app/node_modules
            key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            run: |
              echo ${{needs.install-deps.outputs.outputs1}}
  





