name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS


on:
  workflow_dispatch:
    inputs:
     base-branch:
      type: string
      description: The branch used as the base for the dependency update checks
      default: main
      required: false
     target-branch:
      type: string
      description: The branch from which the PR is created
      default: update-dependencies
      required: false
     working-dir:
      description: The working directory of the project to check for dependency updates.
      required: true
     debug:
      description: Whether the output debug messages to the console.
      default: false
    

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
      - name: check for dependency updates
        uses: ./.github/actions/js-dependency-update
    
    
